version: '3.5'

networks:
    semantics:
        name: semantics
        driver: bridge

services:
    jena_fuseki:
        container_name: jena_fuseki
        image: stain/jena-fuseki
        ports:
            - '3030:3030'
        volumes:
            - './fuseki:/fuseki'
        environment:
            - ADMIN_PASSWORD=password
        networks:
            - semantics

    semantic_project:
        container_name: semantic_project
        build: ../semantic_project
        ports:
            - 4100:80
        volumes:
            - ./nginx/conf/portal.conf:/etc/nginx/sites-enabled/default.conf
            - ../portal/symfony:/var/www/html
        environment:
            - APP_ENV=dev
            - ENABLE_XDEBUG=1
            - PHP_MEM_LIMIT=2048
        networks:
            - semantics

volumes:
    jena_fuseki:
        driver: local
